# Generated by Django 4.1.4 on 2022-12-09 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4, message='Серия карты должна содержать 4 символа'), django.core.validators.RegexValidator(message='Серия карты должна содержать 4 латинских символа в верхнем регистре', regex='[A-Z]{4}')], verbose_name='Серия карты')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер карты')),
                ('discount_amount', models.PositiveSmallIntegerField(verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Карта активна?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карты')),
                ('card_experation', models.CharField(choices=[('1MON', '1 Month'), ('6MON', '6 Month'), ('12MON', '12 Month')], default='1MON', max_length=15, verbose_name='Срок действия')),
                ('end_at', models.DateTimeField(verbose_name='Дата окончания действия карты')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ('-created_at',),
                'unique_together': {('series', 'number')},
                'index_together': {('series', 'number')},
            },
        ),
    ]
