# Generated by Django 4.1.4 on 2022-12-09 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Серия карты должна содержать 4 латинских символа в верхнем регистре', regex='[A-Z]{4}')], verbose_name='Серия карты')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер карты')),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('is_active', models.BooleanField(default=False, verbose_name='Карта активна?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания карты')),
                ('card_experation', models.CharField(choices=[('1', '1 Месяц'), ('6', '6 Месяцев'), ('12', '12 Месяцев')], default='1', max_length=15, verbose_name='Срок действия')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'ordering': ('-created_at',),
                'unique_together': {('series', 'number')},
                'index_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='CardUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата использования карты')),
                ('operation_sum', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма операции')),
                ('place', models.CharField(max_length=200, verbose_name='Место совершения операции')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cards.card', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Запись о использовании карты',
                'verbose_name_plural': 'Записи о использовании карты',
                'ordering': ('-created_at',),
            },
        ),
    ]
