# Generated by Django 4.1.4 on 2022-12-09 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='end_at',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_experation',
            field=models.CharField(choices=[('1', '1 Месяц'), ('6', '6 Месяцев'), ('12', '12 Месяцев')], default='1MON', max_length=15, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='card',
            name='series',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Серия карты должна содержать 4 латинских символа в верхнем регистре', regex='[A-Z]{4}')], verbose_name='Серия карты'),
        ),
    ]
