# Generated by Django 4.1.4 on 2022-12-09 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_end_at_alter_card_card_experation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_experation',
            field=models.CharField(choices=[('1', '1 Месяц'), ('6', '6 Месяцев'), ('12', '12 Месяцев')], default='1', max_length=15, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='card',
            name='discount_amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки'),
        ),
    ]
